### ISSUE TITLE
Update instructions to use this plugin

### ISSUE THREAD

**Issue by jm2dev** [alphagov/gradle-gatling-plugin#13]
The instructions provided by the README file led to the following error:

> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find uk.gov:gradle-gatling-plugin:1.1.

Is it mavenLocal() the right repository? There is an old version, 0.3 at bintray.

**Comment by davbo** [comment]
Hi @jm2dev,

The default build tasks for gradle-gatling-plugin include pushToMavenLocal, so if you clone the repository and run ./gradlew it will build & push the artifact to mavenLocal. The instructions in the  README should work once that is done.

I'll update the README with a step to build the project.

Thanks for spotting this.
