### ISSUE TITLE
Exception in thread "main" java.nio.file.NoSuchFileException: target/test-classes

### ISSUE THREAD

**Issue by Alexey-Stepanov** [alphagov/gradle-gatling-plugin#15]
Hi, all!

I tried to deal with this Gradle plugin and realized that it has not been updated for a long time (the latest commit was on Feb 16, 2015)

It is necessary to make at least two changes in this plugin:

Number 1.

final String GATLING_VERSION = '2.1.3' should be replaced by final String GATLING_VERSION = '2.2.0-SNAPSHOT'

Number 2.
OK, the above change will allow us to download gatling-charts-highcharts.
But what about the rest of dependencies?

For example, I observed the following errors:
Could not resolve all dependencies for configuration ':testCompile'.

> Could not find com.nimbusds:nimbus-jose-jwt:2.22.1.
> Could not find org.scala-lang:scala-library:2.11.6
> ........ and so on and so forth

Solution:
Need to add the line “mavenCentral()” to the list of repositories here:

project.repositories {
       **mavenCentral()**
       maven {
          url 'http://repository.excilys.com/content/groups/public'
          url 'https://oss.sonatype.org/content/repositories/snapshots'
       }
    }

After that I run ./gradlew from gradle-gatling-plugin directory once again (this by default places an artifact in mavenLocal)
Using the command “gradle gatlingTest” I finally managed to build .JAR file

But too early to celebrate, because gatling scenarios execution failed:

[ant:scalac] Element '/home/user/TEMP/scala/build/classes/main' does not exist.
[ant:scalac] Element '/home/user/TEMP/scala/build/resources/main' does not exist.
Executing gatling scenarios: [UserPermissionScenario]
Exception in thread "main" java.nio.file.NoSuchFileException: target/test-classes

Could you help solve this issue?

**Comment by shavo007** [comment]
I got this issue too.

I had to create dir target/test-classes and copy the compiled class file from build/classes here.
I am using the latest version 1.2-SNAPSHOT.

Will this be fixed? 
Should it not be looking in build/classes instead?

**Comment by alxndrsn** [comment]
Hi Alexey, I'm not the maintainer but I doubt there would be an official release which had SNAPSHOT dependencies.  Perhaps a way to manually override the gatling version in your project's gradle file could be provided.

**Comment by alxndrsn** [comment]
@shavo007 please submit a pull request if you have a working patch

**Comment by shavo007** [comment]
Hi @alxndrsn ,

I didn't make a code change. It was a hack locally to get it to work! 

It seems to me that even tho this is a gradle plugin and it should be looking inside build/classes, its expecting the maven folder structure of target/test-classes?

**Comment by cloudbring** [comment]
I'm seeing the same problem.  It is looking for `target/test-classes` instead of `build/test-classes`

**Comment by ChristophSchaal** [comment]
You need to **explicitly set the binaries folder** either in gatling.conf or via command line (-bf or -sbf depending on the version you are using) **to sourceSets.test.output.classesDir** if you are using gradle.

**Comment by willp-bl** [comment]
This should be fixed on the master branch
